name: Build APK (Simple)

on:
  workflow_dispatch: # Manual trigger only
    inputs:
      build_type:
        description: 'Build type'
        required: true
        default: 'debug'
        type: choice
        options:
        - debug
        - release

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install dependencies
      run: npm install

    - name: Create dummy Google Services (for build)
      run: |
        mkdir -p android/app
        echo '{"project_info":{"project_number":"123","project_id":"dummy"},"client":[{"client_info":{"mobilesdk_app_id":"1:123:android:123","android_client_info":{"package_name":"com.minihabittracker"}},"oauth_client":[],"api_key":[{"current_key":"dummy"}],"services":{"appinvite_service":{"other_platform_oauth_client":[]}}}],"configuration_version":"1"}' > android/app/google-services.json

    - name: Make gradlew executable
      run: chmod +x android/gradlew

    - name: Build APK
      run: |
        cd android
        ./gradlew assemble${{ github.event.inputs.build_type == 'release' && 'Release' || 'Debug' }} --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: mini-habit-tracker-${{ github.event.inputs.build_type }}
        path: android/app/build/outputs/apk/${{ github.event.inputs.build_type }}/app-${{ github.event.inputs.build_type }}.apk
        retention-days: 30